import React from 'react';
import type { Metadata } from 'next';
import styles from './layout.module.css';

export const metadata: Metadata = {
	title: '秋瑾的个人主页',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className={styles.profileLayout}>
			<div>{children}</div>
		</div>
	);
}
