import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: '秋瑾的个人主页',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<div>{children}</div>
		</>
	);
}
